name: Build Windows EXE

on:
  push:
    tags:
      - '*'

permissions:
  contents: write
  
jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-python@v6
        with:
          python-version: "3.11"

      - run: pip install pyinstaller

      - run: pip install -r requirements.txt

      - run: pyinstaller --onefile umapi-getusers.py

      - name: Create ZIP package
        run: |
          powershell Compress-Archive -Path dist\*.exe -DestinationPath dist\windows-exe-${{ github.ref_name }}.zip

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          files: dist/windows-exe-${{ github.ref_name }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
